college=input("enter your college name")
city=input("enter your city name")
contact= input("enter your college contact number")
location= input("enter the location of the college")
usn = input("enter usn")

print("college basic details",collage ""+city)
print("college contact is",contact)
print("loction of the college",location)
print ("USN",usn)
